from firedrake import Function, as_vector, CheckpointFile
from firedrake.ml.pytorch import to_torch, from_torch
from torch.nn import Module, Sequential, Linear, ReLU
from torch.utils.data import DataLoader, Dataset

from collections import namedtuple
import numpy as np
import os
import torch


class HybridModel(object):

    def __init__(self, pde_model, ml_model, fields_to_adjust,
                 data_dir, point_training_data_file,
                 point_test_data_file, global_training_data_file,
                 global_test_data_file):
        """
        Args:
            pde_model: PDE model (Gusto model class?)
            ml_model: PyTorch model
            fields_to_adjust (list): list of names of fields to adjust
                with ml model
            data_dir (str): directory where to save / load data to / from
            data_file (str): name of
        """

        self.fields_to_adjust = fields_to_adjust

        batch_size = 1

        # Create dataset classes and dataloader classes for reading in
        # test and training data
        self.point_train_dataset = PointDataset(
            numpy_data=os.path.join(data_dir, point_training_data_file),
            data_dir=data_dir
        )
        self.train_point_dl = DataLoader(self.point_train_dataset,
                                         batch_size=batch_size,
                                         shuffle=False)
        self.point_test_dataset = PointDataset(
            numpy_data=os.path.join(data_dir, point_test_data_file),
            data_dir=data_dir
        )
        self.test_point_dl = DataLoader(self.point_test_dataset,
                                        batch_size=batch_size,
                                        shuffle=False)
        self.global_train_dataset = GustoGlobalDataset(
            dataset=os.path.join(data_dir, self.global_training_data_file),
            data_dir=data_dir
        )
        self.train_global_dl = DataLoader(
            self.global_train_dataset,
            batch_size=batch_size,
            collate_fn=self.global_train_dataset.collate,
            shuffle=False)
        self.global_test_dataset = GustoGlobalDataset(
            dataset=os.path.join(data_dir, self.global_testdata_file),
            data_dir=data_dir
        )
        self.test_global_dl = DataLoader(
            self.global_test_dataset,
            batch_size=batch_size,
            collate_fn=self.global_test_dataset.collate,
            shuffle=False)

        # Set double precision in ml_model to match types
        ml_model.double()
        # Move ml_model to device
        device = "cpu"
        ml_model.to(device)

        fs = self.train_global_dl.dataset.fs
        self.ml_out = Function(fs)
        self.prediction = Function(fs)

    def cost_function(self):
        """
        ML cost function
        """

    def assemble_prediction(self, dyn, ml):
        """
        This adds the ml prediction to the dynamics predictions
        """

        ml_idx = 0
        for field_name in self.fields_to_adjust:
            idx = self.pde_model.equation.field_names.index(field_name)
            if field_name == "u":
                self.ml_out.subfunctions[idx].project(
                    as_vector([ml[ml_idx], ml[ml_idx+1]])
                )
                ml_idx += 2
            else:
                self.ml_out.subfunctions[idx].interpolate(ml[ml_idx])
                ml_idx += 1

        self.prediction.interpolate(dyn + self.ml_out)

    def forward_pass(self):
        """
        Forward pass of the ml model. Returns a list of tensors.
        """

    def generate_data(self):
        """
        Generate data using the forward model.
        """

    def train(self):
        """
        Train the hybrid model.
        """

    def evalute(self, filename=None):
        """
        Evaluate the hybrid model
        Args:
            filename (str, optional): where to find validation data. Defaults
            to None in which case use validation data generated by
            generate_data method
        """


class GustoGlobalDataset(Dataset):

    def __init__(self, dataset, data_dir, field_names, attr_names):
        """
        Args:
            dataset (string): the name of the .h5 file with the data
            data_dir (string): the path to where the data are saved
        """
        # Check dataset directory
        data_file = os.path.join(data_dir, dataset)
        if not os.path.exists(data_file):
            raise ValueError(f"Dataset directory {os.path.abspath(data_file)} does not exist")

        # Get mesh and batch elements (Firedrake functions)
        self.attr_items = attr_names
        data = []
        with CheckpointFile(data_file, "r") as afile:
            n = int(np.array(afile.h5pyfile["n"]))
            # Load mesh
            mesh = afile.load_mesh("mesh")
            # Load data
            fields = []
            attrs = []
            for i in range(n):
                for field_name in field_names:
                    fields.append(afile.load_function(
                        mesh, field_name, idx=i))
                for attr_name in attr_names:
                    attrs.append(afile.get_attr("/", key=attr_name))

                data.append(tuple(fields + attrs))

        self.mesh = mesh

        self.field_names = field_names
        self.batch_elements_fd = data
        self.fs = self.batch_elements_fd[0][0].function_space()

    def __len__(self):
        return self.batch_elements_fd

    def __getitem__(self, idx):
        """
        Args:
            idx (float): the index of the sample
        """
        batch_element = self.batch_elements_fd[idx]
        name_list = []
        values = []
        # Convert Firedrake functions to PyTorch tensors
        for be in batch_element:
            if isinstance(be, Function):
                name_list.append(be.name)
                values.append(to_torch(be))
                name_list.append(be.name+"_fd")
                values.append(be)
            else:
                name_list.append(be.key)
                values.append(be)

        name_list.append("idx")
        values.append(idx)

        BatchElement = namedtuple("BatchElement", name_list)
        BatchElement(*values)

        return BatchElement

    def collate(self, batch_elements):

        BatchedElement
        return BatchedElement


class PointDataset(Dataset):
    """
    Dataset reader for data generated point-wise from a PDE
    solution. The pointwise data should be saved as numpy arrays.
    """

    def __init__(self, numpy_data, data_dir=None):
        """
        Args:
            numpy_data (string): the name of the .npy file with the data
            data_dir (string, optional): the path to where the numpy data are saved
        """
        # Check dataset directory
        if data_dir is not None:
            dataset_dir = os.path.join(data_dir, "datasets", numpy_data)
            if not os.path.exists(dataset_dir):
                raise ValueError(f"Dataset directory {os.path.abspath(dataset_dir)} does not exist")
            self.numpy_list = np.load(numpy_data)
        else:
            self.numpy_list = numpy_data

    def __len__(self):
        return len(self.numpy_list)

    def __getitem__(self, idx):
        """
        Args:
            idx (float): the index of the sample
        """
        # Make the sample a numpy array first
        numpy_sample = np.array(self.numpy_list[idx])
        # Convert the numpy array to a PyTorch tensor
        tensor_sample = torch.from_numpy(numpy_sample)
        return tensor_sample


class PointNN(Module):
    """A simple nn-based model to deal with general point-based problems"""

    def __init__(self, n_in, n_out):
        """
        Args:
            n_in (int): number of input parameters
            n_out (int): number of output parameters
        """

        super().__init__()

        self.nn_encoder = Sequential(Linear(n_in, 32),
                                     ReLU(True),
                                     Linear(32, 64),
                                     ReLU(True),
                                     Linear(64, 128),
                                     ReLU(True))

        self.nn_decoder = Sequential(Linear(128, 64),
                                     ReLU(True),
                                     Linear(64, 32),
                                     ReLU(True),
                                     Linear(32, n_out))

    def forward(self, input_tensor):

        # CNN encoder-decoder
        z = self.nn_encoder(input_tensor)
        y = self.nn_decoder(z)

        return y
