workspace:
  base: /drone
  path: src

pipeline:
  build:
    image: ubuntu:xenial
    pull: true
    environment:
      # Change the following to reflect your local preferences
      - PACKAGE=gusto
      - GUSTO_HOME=/drone/install
      - GUSTO_GID=1000
      - GUSTO_UID=1000
      - CC=mpicc
      - GIT_SOURCE_DIR=/drone/src
    commands:
      # Bring the image up to date
      - apt-get -y update
      - apt-get -y dist-upgrade

      # Install dependencies for a single run of firedrake-install
      - apt-get -y install sudo python-minimal python-pip curl

      # Fail fast on lint errors
      - pip install -U flake8
      - pip install pep8-naming
      - cd $GIT_SOURCE_DIR
      - make lint
      - pip install virtualenv

      # Make a firedrake user to run the tests
      - mkdir $GUSTO_HOME
      - groupadd -g $GUSTO_GID gusto
      - useradd -d $GUSTO_HOME -u $GUSTO_UID -g $GUSTO_GID gusto

      # Passwordless sudo: \072 is octal for :
      # Colon breaks the drone yaml parser
      - /bin/echo -e "gusto ALL=NOPASSWD\072 ALL\n" >> /etc/sudoers

      # Install firedrake
      - cd $GUSTO_HOME
      - curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
      - python ./firedrake-install --disable-ssh --minimal-petsc
      - . ./firedrake/bin/activate
      - pip install -e $GIT_SOURCE_DIR/

      # We're going to run the tests as the gusto user, so get permissions right.
      - chown -R gusto.gusto $GUSTO_HOME

      - cd $GUSTO_HOME
      # Run tests as the gusto user, pushing in the current path.
      - sudo -EHu gusto env PATH="$PATH" py.test -n 4 -v $GIT_SOURCE_DIR/tests/
  # Slack notification
  slack:
    image: plugins/slack
    channel: drone
    user: drone
    when:
      status: [ success, failure ]
