"""
Tests the MonotonicMeanLimiter against fields generated by genuine
(unlimited) conservative transport of a density and an associated mixing
ratio on an extruded vertical-slice mesh, under solid body rotation. This
exercises the limiter's support for extruded meshes, for both the
'relaxed' (CG1) and 'facet' (tensor-product hybrid) extruded_bounds_method
options.
"""

from gusto import *
from firedrake import (as_vector, PeriodicIntervalMesh, pi, SpatialCoordinate,
                       ExtrudedMesh, FunctionSpace, Function, conditional,
                       sqrt, sin, cos, assemble, dx)
import numpy as np
import pytest


def setup_unlimited_conservative_transport(dirname):
    """
    Sets up conservative transport of a density (rho_d) and a discontinuous
    mixing ratio (m_X) on an extruded vertical-slice mesh, using solid body
    rotation for the velocity field, with no limiter attached to the
    transport scheme. This is used to generate genuine (non-synthetic)
    pre- and post-transport fields to test the MonotonicMeanLimiter
    against on an extruded mesh.
    """

    Ld = 1.
    tmax = 0.2
    dt = tmax / 40
    rotations = 0.25

    m = PeriodicIntervalMesh(20, Ld)
    mesh = ExtrudedMesh(m, layers=20, layer_height=(Ld/20))

    domain = Domain(mesh, dt, family="CG", degree=1)
    V = domain.spaces('DG')
    Vu = domain.spaces('HDiv')
    Vpsi = domain.spaces('H1')

    rho_d = ActiveTracer(name='rho_d', space='DG',
                         variable_type=TracerVariableType.density,
                         transport_eqn=TransportEquationType.conservative)
    m_X = ActiveTracer(name='m_X', space='DG',
                       variable_type=TracerVariableType.mixing_ratio,
                       transport_eqn=TransportEquationType.tracer_conservative,
                       density_name='rho_d')

    eqn = CoupledTransportEquation(domain, active_tracers=[rho_d, m_X], Vu=Vu)

    output = OutputParameters(dirname=dirname+'/unlimited_conservative',
                              dumpfreq=1, dumplist=['u', 'rho_d', 'm_X'])
    io = IO(domain, output)

    # No limiter attached, so that m_X is free to develop over/undershoots
    transport_scheme = SSPRK3(domain, rk_formulation=RungeKuttaFormulation.predictor)
    transport_method = [DGUpwind(eqn, 'rho_d'), DGUpwind(eqn, 'm_X')]

    stepper = PrescribedTransport(
        eqn, transport_scheme, io, False, transport_method
    )

    # ------------------------------------------------------------------------ #
    # Initial conditions
    # ------------------------------------------------------------------------ #

    rho0 = stepper.fields('rho_d', V)
    mX0 = stepper.fields('m_X', V)

    x, z = SpatialCoordinate(mesh)

    # Smooth, strictly positive density field
    rho0.interpolate(Constant(1.0) + 0.5*sin(2*pi*x/Ld)*cos(pi*z/Ld))

    tracer_min = 12.6
    dtracer = 3.2

    x1_lower = 2 * Ld / 5
    x1_upper = 3 * Ld / 5
    z1_lower = 6 * Ld / 10
    z1_upper = 8 * Ld / 10

    expr = conditional(x > x1_lower,
                       conditional(x < x1_upper,
                                   conditional(z > z1_lower,
                                               conditional(z < z1_upper, dtracer, 0.0),
                                               0.0),
                                   0.0),
                       0.0)

    mX0.interpolate(Constant(tracer_min) + expr)

    # ------------------------------------------------------------------------ #
    # Velocity profile: solid body rotation
    # ------------------------------------------------------------------------ #

    psi = Function(Vpsi)
    u = stepper.fields('u')

    xc = Ld / 2
    zc = Ld / 2
    r = sqrt((x - xc) ** 2 + (z - zc) ** 2)
    omega = rotations * 2 * pi / tmax
    r_out = 9 * Ld / 20
    r_in = 2 * Ld / 5
    A = omega * r_in / (2 * (r_in - r_out))
    B = - omega * r_in * r_out / (r_in - r_out)
    C = omega * r_in ** 2 * r_out / (r_in - r_out) / 2
    psi_expr = conditional(r < r_in,
                           omega * r ** 2 / 2,
                           conditional(r < r_out,
                                       A * r ** 2 + B * r + C,
                                       A * r_out ** 2 + B * r_out + C))
    psi.interpolate(psi_expr)

    gradperp = lambda v: as_vector([-v.dx(1), v.dx(0)])
    u.project(gradperp(psi))

    return stepper, dt, V


@pytest.mark.parametrize('extruded_bounds_method', ['relaxed', 'facet'])
def test_monotonic_mean_limiter_extruded(tmpdir, extruded_bounds_method):
    """
    Tests the MonotonicMeanLimiter against fields generated by genuine
    (unlimited) conservative transport of a density and a discontinuous
    mixing ratio on an extruded mesh, which is expected to produce
    over/undershoots in the mixing ratio (Gibbs oscillations). Checks that
    applying the limiter substantially reduces the over/undershoot relative
    to the initial condition, and that mass is conserved, for both the
    'relaxed' and 'facet' extruded_bounds_method options.

    The pre-transport field used for the monotonic bounds is the pristine
    initial condition (before any transport has occurred). The limiter only
    guarantees monotonicity relative to the min/max of the pre-transport
    field over each cell and its facet-neighbours (and assumes the
    mass-consistent mean lies within those local bounds); for a genuinely
    discontinuous field at finite resolution this local assumption can be
    violated right at the sharpest gradients, so a substantial-reduction
    check is used here rather than requiring the over/undershoot to be
    eliminated entirely.
    """

    dirname = str(tmpdir)
    stepper, dt, V = setup_unlimited_conservative_transport(dirname)

    # The pristine initial condition, before any transport has occurred
    old_field = Function(V).assign(stepper.fields('m_X'))
    old_min = np.min(old_field.dat.data)
    old_max = np.max(old_field.dat.data)

    # Take one (unlimited) step to generate a genuine post-transport,
    # pre-limiting field
    stepper.run(t=0, tmax=dt)
    new_field = stepper.fields('m_X')

    # Sanity check: unlimited transport of this discontinuous field should
    # have produced some new over/undershoot relative to the initial
    # condition (Gibbs oscillations from unlimited DG1 transport)
    unlimited_overshoot = max(np.max(new_field.dat.data) - old_max, 0.0)
    unlimited_undershoot = max(old_min - np.min(new_field.dat.data), 0.0)
    assert unlimited_overshoot > 1e-3 or unlimited_undershoot > 1e-3, \
        'Test setup should produce genuine over/undershoots for the limiter to fix'

    # A conservative, mass-consistent mean companion field: since there is
    # no density-weighting in the limiter itself, this is simply the cell
    # average of the mixing ratio
    DG0 = FunctionSpace(V.mesh(), 'DG', 0)
    mean_field = Function(DG0).project(new_field)

    mass_before = assemble(new_field*dx)

    limiter = MonotonicMeanLimiter([V], extruded_bounds_method=extruded_bounds_method)
    limited_field = Function(V).assign(new_field)
    limiter.apply([limited_field], [mean_field], [old_field])

    # The limiter only guarantees that the limited field in each cell lies
    # within the min/max of the pre-transport field over that cell and its
    # facet-neighbours, and this in turn assumes that the (mass-consistent)
    # mean lies within those local bounds. For a genuinely discontinuous
    # field transported at finite resolution, this assumption can be
    # locally violated right at the sharpest gradients, so rather than
    # requiring the global over/undershoot to be eliminated entirely, check
    # that it has been substantially reduced compared to the unlimited field.
    limited_overshoot = max(np.max(limited_field.dat.data) - old_max, 0.0)
    limited_undershoot = max(old_min - np.min(limited_field.dat.data), 0.0)

    assert limited_overshoot < 0.7*unlimited_overshoot, \
        'MonotonicMeanLimiter has not substantially reduced overshoots in a transport problem'
    assert limited_undershoot < 0.7*unlimited_undershoot, \
        'MonotonicMeanLimiter has not substantially reduced undershoots in a transport problem'

    # Check that the limiter actually changed the field (i.e. it is not a
    # no-op on this genuinely violating data)
    assert not np.allclose(limited_field.dat.data, new_field.dat.data), \
        'MonotonicMeanLimiter did not modify the overshooting/undershooting field'

    # Check mass conservation
    mass_after = assemble(limited_field*dx)
    assert np.isclose(mass_before, mass_after, atol=1e-10), \
        'MonotonicMeanLimiter did not conserve mass in a transport problem'
