name: Check docs build cleanly

on:
  # Run on pushes to master
  push:
    branches:
      - master
  # And all pull requests
  pull_request:

concurrency:
  # Cancels jobs running if new commits are pushed
  group: >
    ${{ github.workflow }}-
    ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_docs:
    name: Run doc build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # The docker container to use.
    container:
      image: firedrakeproject/firedrake-docdeps:latest
      options: --user root
      volumes:
        - ${{ github.workspace }}:/home/firedrake/output
    # Steps represent a sequence of tasks that will be executed as
    # part of the jobs
    steps:
      - uses: actions/checkout@v3
      - name: Install checkedout Gusto
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pip install -e .
      - name: Install Read the Docs theme
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pip install sphinx_rtd_theme
      - name: Check documentation links
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          . /home/firedrake/firedrake/bin/activate
          cd docs
          make linkcheck
      - name: Build docs
        run: |
          . /home/firedrake/firedrake/bin/activate
          cd docs
          make html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: /__w/gusto/gusto/docs/build/html
          retention-days: 1
