name: Run lint

on:
  # Push to master or PR
  push:
    branches:
      - master
  pull_request:

jobs:
  linter:
    name: "Run linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1
      - name: Install linter
        run: |
          pip install flake8 pylint
      - name: Lint codebase
        run: |
          make lint GITHUB_ACTIONS_FORMATTING=1
  actionlint:
    name: "Lint Github actions YAML files"
    # There's a way to add error formatting so GH actions adds messages to code,
    # but I can't work out the right number of quotes to get it to work
    # https://github.com/rhysd/actionlint/blob/main/docs/usage.md
    # #example-error-annotation-on-github-actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
