"""
Defines a simple linear decay physics parametrisation, used as a test case for
checking that physics parametrisations are being correctly evaluated within
the Runge-Kutta time discretisations.
"""

from firedrake import Function, dx, Constant, split, interpolate, assemble
from firedrake.fml import subject
from gusto.core.labels import source_label
from gusto.core.logging import logger
from gusto.physics.physics_parametrisation import PhysicsParametrisation

__all__ = ["LinearDecay"]


class LinearDecay(PhysicsParametrisation):
    """
    A simple linear decay/relaxation process, representing:

    dq/dt = -k*q

    for some prognostic variable q and a (positive) decay rate k. This is a
    deliberately simple physics scheme -- it exists so that the analytic
    solution q(t) = q(0)*exp(-k*t) can be compared against the numerical
    solution, in order to test that physics parametrisations are correctly
    evaluated within the different Runge-Kutta formulations.
    """

    def __init__(self, equation, variable_name, k, method='interpolate'):
        """
        Args:
            equation (:class:`PrognosticEquation` or :class:`PrognosticEquationSet`):
                the model's equation.
            variable_name (str): the name of the variable to apply the decay to.
            k (float or :class:`Constant`): the decay rate, which should be a
                positive number if `q` is to decay.
            method (str, optional): the method to use to evaluate the source
                expression. Valid options are 'interpolate' or 'project'.
                Defaults to 'interpolate'.
        """

        label_name = f'linear_decay_{variable_name}'
        super().__init__(equation, label_name, parameters=None)

        if method not in ['interpolate', 'project']:
            raise ValueError(f'Method {method} for source evaluation not valid')
        self.method = method
        self.variable_name = variable_name
        self.k = Constant(k) if not isinstance(k, Constant) else k

        # Check the variable exists
        if hasattr(equation, "field_names"):
            assert variable_name in equation.field_names, \
                f'Field {variable_name} does not exist in the equation'
        else:
            assert variable_name == equation.field_name, \
                f'Field {variable_name} does not exist in the equation'

        # Store a copy of the current field, used to evaluate k*q
        self.X = Function(equation.X.function_space())

        # Work out the appropriate function space and test function
        if hasattr(equation, "field_names"):
            self.V_idx = equation.field_names.index(variable_name)
            W = equation.function_space
            V = W.sub(self.V_idx)
            test = equation.tests[self.V_idx]
            variable = split(self.X)[self.V_idx]
            self.source = Function(W)
            self.source_expr = split(self.source)[self.V_idx]
            self.source_int = self.source.subfunctions[self.V_idx]
        else:
            V = equation.function_space
            test = equation.test
            variable = self.X
            self.source = Function(V)
            self.source_expr = self.source
            self.source_int = self.source

        # The source/sink term added to the residual represents the negative
        # of dq/dt (matching the convention used by the `SourceSink` physics
        # scheme), so to obtain dq/dt = -k*q we add the (positive) expression
        # k*q as the source term.
        rate_expression = self.k * variable

        # Add the source term to the equation's residual
        equation.residual += source_label(
            self.label(subject(test * self.source_expr * dx, self.source), self.evaluate)
        )

        # Handle method of evaluating source
        if self.method == 'interpolate':
            self.source_interpolate = interpolate(rate_expression, V)
        else:
            from firedrake import Projector
            self.source_projector = Projector(rate_expression, self.source_int)

    def evaluate(self, x_in, dt, x_out=None):
        """
        Evaluates the source term generated by this physics scheme.

        Args:
            x_in (:class:`Function`): the (mixed) field to be evolved.
            dt (:class:`Constant`): the timestep, or time interval for the
                scheme. Unused, as this scheme does not depend explicitly on dt.
            x_out (:class:`Function`, optional): the (mixed) source field to
                be output to. Defaults to None.
        """
        logger.info(f'Evaluating physics parametrisation {self.label.label}')
        self.X.assign(x_in)
        if self.method == 'interpolate':
            assemble(self.source_interpolate, tensor=self.source_int)
        else:
            self.source_projector.project()

        # If a source output is provided, assign the source term to it
        if x_out is not None:
            x_out.assign(self.source)
